# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Set environment variables if needed
ENV NODE_ENV=production

# Expose port if used by server (optional; MCP typically runs on stdio)

# Start the server
CMD [ "node", "dist/index.js" ]
